name: Build

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    uses: JappeOS/jappeos-workflows/.github/workflows/build-package.yml@main
    with:
      package-name: jappeos-terminal
      flutter: true
    secrets: inherit