name: Release

on:
  push:
    branches: ["dev", "testing", "stable"]
    paths:
      - "pubspec.yaml"

permissions:
  contents: write

jobs:
  release:
    uses: JappeOS/jappeos-workflows/.github/workflows/release-flutter.yml@main
    secrets: inherit
  build:
    needs: release
    uses: JappeOS/jappeos-workflows/.github/workflows/build-package.yml@main
    with:
      package-name: jappeos-terminal
      flutter: true
    secrets: inherit